### ISSUE TITLE
Provide an API allowing workflow: user puts in the money and scans QR code later

### ISSUE THREAD

**Issue by Kixunil** [GENERALBYTESCOM/batm_public#154]
Provide an API that allows inserting money without showing QR code to the machine and show a QR code on the screen after the user clicks "Buy" button.

This would enable the ATM to directly open a pre-funded Lightning Network channel with the user, saving one on-chain transaction (with associated fees and waiting time) and after relevant changes to the LN infrastructure even enable safely doing zeroconf LN transactions.

This would help Paralelna Polis greatly, but also enable other use cases (e.g. buy bitcoins and immediately use them to buy something online that's not easily buyable using fiat money).

**Comment by chrisrico** [comment]
Couldn't you use the current flow, but instead of scanning a Bitcoin address, you scan a node ID (pubkey@IP:port)? It's likely you can look up their IP by their pubkey, so just their pubkey should suffice.

The user might already have a Lightning channel open, in which case you would want to pay an invoice instead of opening a new channel. So this flow should accept both pubkeys (for opening a channel) and invoices (for paying over an existing channel) and should be able to determine which path to follow based on the type scanned.

According to the [Lightning spec](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#human-readable-part), invoices can be without an amount (set to 0) in which case any payment is accepted. This is important because with the customer generating the invoice, it would otherwise have an exact amount of satoshis set, where we won't know the amount we're sending until after they finish inserting cash.

**Comment by Kixunil** [comment]
The current flow is unusable if the user has mobile wallet (e.g. BLW), which is likely behind NAT or firewall. LNURL was designed to solve this, but it requires opposite flow.

Currently, majority of people don't have a full node with public IP.

**Comment by generalbytes** [comment]
Please use standard feature requests flow via GB support department via support@generalbytes.com 
I'm closing this issue as only issues regarding opensource part should be here.
