### ISSUE TITLE
Exchange implemenation

### ISSUE THREAD

**Issue by PatrycjaFTO** [GENERALBYTESCOM/batm_public#159]
We have a question regarding Coindeal exchange implementation in ATM. We can see that in open source part all exchanges are using XChange library
https://github.com/knowm/XChange to implement abstract logic. Is it ok for you to do the integration in the same way? 
I mean in first step integrate with mentioned library and after that create PR to https://github.com/GENERALBYTESCOM/batm_public?

**Comment by PatrycjaFTO** [comment]
@rpanak-generalbytes Could we get answer please?

**Comment by rpanak-generalbytes** [comment]
@PatrycjaFTO I'm not sure ALL exchanges do that. However, you can use that library if necessary. Please note the library version in use is not the latest one. We are in the process of updating to the latest version, but we can't tell you when the latest version will be ready.

**Comment by PatrycjaFTO** [comment]
@rpanak-generalbytes Is there any testing environment online that we can use, while writing the code?  Or do we have to have spare ATM for that?

**Comment by rpanak-generalbytes** [comment]
There is a tester project in this repository. However, it does only very basic testing. It can only display a conversion rate or wallet/exchange balance. In the beginning, this might be enough, but for proper testing, an ATM is the best. There is no online testing environment.

**Comment by PatrycjaFTO** [comment]
@rpanak-generalbytes 
One more question. Is it possible to make a build for ATM from our side? It means that we need to test during development process and put compiled code into ATM before creating final PR to your repository

**Comment by rpanak-generalbytes** [comment]
No. However, you shouldn't need it. The code from this repository is just server-side code. You can build the extension JAR and put it into a compatible server installation yourself. In case you are using the latest changes from our repository, you might need to wait a little for a release that's compatible with the repository. It all depends whether any breaking changes have been merged into the repository recently.
However, you can always branch off the code from an older commit, that's compatible with an available server version. I wouldn't recommend this though, because you'll have to merge in the compatibility breaking commits anyway. We release new versions quite often though (at least once every 2 weeks, usually more often), so waiting shouldn't be a big problem.

**Comment by rpanak-generalbytes** [comment]
More than a week of inactivity after all questions answered. Closing.
