### ISSUE TITLE
Coin is not showing in CAS

### ISSUE THREAD

**Issue by wvabitpal** [GENERALBYTESCOM/batm_public#186]
Hi, I have added our coin and did all the codes, added the name in CryptoCurrency.java but still it is now showing in CAS, anything I have missed? It is woking in your old code but when I transfered it in your latest commit where CrytoCurrency and FiatCurrency is already separated it is no longer showing. please help. @generalbytes  @rpanak-generalbytes

**Comment by rpanak-generalbytes** [comment]
Hi, we've refactored a part of the code regarding currencies. In the current state, you can either repack the CAS WAR file (can be found in /batm/app/admin/standalone/deployments/batm_server_admin.war) and update the currencies.jar with a new version containing your coin (you can build this jar from the code in this repo) or wait until we fix this in the next release. Beware that the repackaging won't be supported by us, so if you choose to go this way, you're on your own. I'd recommend waiting for the next release.

**Comment by int3hh** [comment]
Could you please push to the master branch when building the project actually works on CAS ? Or you start work from end to beginning ? When is this release due ? I don't want to sound impolite but this stammering is costing us money.

**Comment by rpanak-generalbytes** [comment]
> Could you please push to the master branch when building the project actually works on CAS ?

Building the project actually works.
> Or you start work from end to beginning ?

No, it's the other way around.
> When is this release due ?

A regular release is planned for next week. We'll discuss a possibility of hotfix release sooner. 

> I don't want to sound impolite but this stammering is costing us money.

Please be aware that this is an open source project. We do offer paid development services, but try to provide an alternative for the community. I'd say by opening the sources we're **saving** you money. While mistakes do happen, they're definitely not intentional.

**Comment by wvabitpal** [comment]
Hi, it is working now with server version 20190319. cheers!
