### ISSUE TITLE
Extensions logging

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#357]
Hello, i have add an REST extension on my batm-server and i am trying to log the REST output on a file.The thing is that this file is never created when i am putting the .jar file on the extension folder. On my local desktop it works fine. Do you know if this has to do with permission when the server runs the extension? Thank you

**Comment by generalbytes** [comment]
Logging framework that your extension is using is probably reading logging configuration from your jar when you are developing extension. 
But when extension is run inside of the server logging framework probably reads configuration from different jar because your extension is loaded after the server starts and logging configuration is already loaded.

**Comment by makarid** [comment]
Thanks a lot. It helped!
